# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec80c1f054d92b6181e9b4fc3cb682d3"
name = "monitor-api-connect"
handle = "monitor-api-connect"
application_url = "https://mariah-myanmar-let-distributor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_customers,write_products,write_customers,read_locations,write_inventory"

[auth]
redirect_urls = [
  "https://mariah-myanmar-let-distributor.trycloudflare.com/auth/callback",
  "https://mariah-myanmar-let-distributor.trycloudflare.com/auth/shopify/callback",
  "https://mariah-myanmar-let-distributor.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
