api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "sonsab-cart-transformer"
type = "function"
uid = "711e72c2-089c-fb2d-6c74-21fea3026e1c15e0a8b2"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
